version: '3'

services:
  api:
    build: ./api
    ports: 
      - "8080:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./web
    ports:
      - "80:3000"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - api